import type { CandidateExamRecord, Exam } from "@/types/exam";

export const mockDb: { exams: Exam[]; candidates: CandidateExamRecord[] } = {
  exams: [
    {
      id: "exam-1",
      title: "Psychometric Test for Management Trainee Officer",
      totalCandidates: 40,
      totalSlots: 2,
      questionSets: 3,
      questionType: "radio",
      startTime: "2026-04-11T09:00:00.000Z",
      endTime: "2026-04-11T11:00:00.000Z",
      duration: 60,
      negativeMarking: true,
      questions: [
        {
          id: "q-1",
          questionTitle: "What does JSX compile to?",
          type: "radio",
          options: ["Functions", "Objects", "HTML", "JS classes"],
        },
        {
          id: "q-2",
          questionTitle: "Which hook is used for local state?",
          type: "radio",
          options: ["useFetch", "useState", "useReducerOnly", "usePortal"],
        },
      ],
    },
    {
      id: "exam-2",
      title: "Psychometric Test for Management Trainee Officer",
      totalCandidates: 48,
      totalSlots: 2,
      questionSets: 2,
      questionType: "radio",
      startTime: "2026-04-12T09:00:00.000Z",
      endTime: "2026-04-12T11:00:00.000Z",
      duration: 30,
      negativeMarking: true,
      questions: [
        {
          id: "q-3",
          questionTitle: "What does CSS stand for?",
          type: "radio",
          options: ["Cascading Style Sheets", "Colorful Style Setup", "Code Style Syntax", "Core Styling Sheet"],
        },
        {
          id: "q-4",
          questionTitle: "Which property controls text size?",
          type: "radio",
          options: ["font-size", "text-style", "size", "font"],
        },
      ],
    },
    {
      id: "exam-3",
      title: "Psychometric Test for Management Trainee Officer",
      totalCandidates: 42,
      totalSlots: 2,
      questionSets: 3,
      questionType: "radio",
      startTime: "2026-04-13T09:00:00.000Z",
      endTime: "2026-04-13T11:00:00.000Z",
      duration: 30,
      negativeMarking: true,
      questions: [
        {
          id: "q-5",
          questionTitle: "What is TypeScript primarily used for?",
          type: "radio",
          options: ["Styling", "Type-safe JavaScript", "Database management", "Image editing"],
        },
        {
          id: "q-6",
          questionTitle: "Which command starts Next.js dev mode?",
          type: "radio",
          options: ["next run", "npm run dev", "npm run next", "next up"],
        },
      ],
    },
    {
      id: "exam-4",
      title: "Psychometric Test for Management Trainee Officer",
      totalCandidates: 55,
      totalSlots: 2,
      questionSets: 4,
      questionType: "radio",
      startTime: "2026-04-14T09:00:00.000Z",
      endTime: "2026-04-14T11:00:00.000Z",
      duration: 30,
      negativeMarking: true,
      questions: [
        {
          id: "q-7",
          questionTitle: "Which is a semantic HTML element?",
          type: "radio",
          options: ["div", "section", "span", "b"],
        },
        {
          id: "q-8",
          questionTitle: "React components should return what?",
          type: "radio",
          options: ["Boolean", "JSX", "Object only", "Array only"],
        },
      ],
    },
  ],
  candidates: [
    {
      id: "cand-1",
      testId: "exam-1",
      candidateName: "Alex Doe",
      email: "alex@example.com",
      status: "completed",
    },
    {
      id: "cand-2",
      testId: "exam-1",
      candidateName: "Sam Lee",
      email: "sam@example.com",
      status: "pending",
    },
  ],
};
